### ISSUE TITLE
Feature: specify Go version in GitHub Action

### ISSUE THREAD

**Issue by hazcod** [bobheadxi/gobenchdata#41]
Hi,

Is there a way to specify the Go version to use when using `gobenchdata`?
e.g.in my case the Go version is pinned down, and I like to see performance changes between Go versions. Thank you!

e.g. https://github.com/ironPeakServices/iron-go-project/blob/master/.github/workflows/build.yml#L20

**Comment by bobheadxi** [comment]
Unfortunately not at the moment - the Go version is baked in: https://github.com/bobheadxi/gobenchdata/blob/master/Dockerfile#L1

but this is a valid use case! I will investigate how to best incorporate this into the default action. In the meantime, you can also use the CLI directly to achieve the exact same behaviour as the Action using your specified version of Go, something like:

```yml
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ steps.vars.outputs.go_version }}
      - name: Install gobenchdata
        run: go get go.bobheadxi.dev/gobenchdata
      - name: Run gobenchdata
        run: go test -bench | gobenchdata --json "${RUN_OUTPUT}" -v "${GITHUB_SHA}" -t "ref=${GITHUB_REF}"
```

or similar - see [entrypoint.sh](https://github.com/bobheadxi/gobenchdata/blob/master/entrypoint.sh#L43-L48) for more details, or feel free to ping back here if you have any questions!
