### ISSUE TITLE
[Checks] Mem.BytesPerOp not supported

### ISSUE THREAD

**Issue by josephgardner** [bobheadxi/gobenchdata#57]
The following check tests for a regression in `Mem.BytesPerOp`. However, the result is always 0.

```
checks:
- name: BytesPerOp
  package: .
  benchmarks: [ '.' ]
  diff: (current.Mem.BytesPerOp - base.Mem.BytesPerOp) / base.Mem.BytesPerOp * 100
  thresholds:
    max: 25
```

Results:

```
{
  "Status": "pass",
  "Checks": {
    "BytesPerOp": {
      "Status": "pass",
      "Diffs": [
        {
          "Status": "pass",
          "Package": "...",
          "Benchmark": "...",
          "Value": 0
        }
      ],
      "Thresholds": {
        "Min": null,
        "Max": 25
      }
    }
  }
}
```

Sample input:

```
[
  {
    "Date": 1651034107,
    "Suites": [
      {
        "Goos": "linux",
        "Goarch": "amd64",
        "Pkg": "...",
        "Benchmarks": [
          {
            "Name": "...",
            "Runs": 5,
            "NsPerOp": 111754445,
            "Mem": {
              "BytesPerOp": 14284630,
              "AllocsPerOp": 503144,
              "MBPerSec": 0
            }
          }
        ]
      }
    ]
  }
]
```
