### ISSUE TITLE
usage with private repo?

### ISSUE THREAD

**Issue by srenatus** [bobheadxi/gobenchdata#66]
Hello! This is a fine tool, and I've enjoyed using it so far, thank you 🎈 

What I didn't get to work is the publishing of the processed benchmark results into another git branch **of a private github repo**. The workflow run ends in
```
Cloning into '.'...
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/cant/tell.git/'
exit status 1
```

My workflow definition is this:

```yaml
      - name: gobenchdata publish
        run: go run go.bobheadxi.dev/gobenchdata@v1 action
        env:
          INPUT_GO_TEST_FLAGS: -timeout=120m
          INPUT_PUBLISH: true
          INPUT_PUBLISH_BRANCH: benchmarks
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        timeout-minutes: 120
```

I also got this in the yaml workflow file:
```yaml
permissions:
  # contents permission to update benchmark contents in 'benchmarks' branch
  contents: write
```
and I'm not entirely sure if "write" implies "read" or if the problem is something else.

FWIW looking at entrypoint.sh, I've found that it's [making a call like
](https://github.com/bobheadxi/gobenchdata/blob/main/entrypoint.sh#L60)
```
git clone https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${INPUT_PUBLISH_REPO}.git .
```
which doesn't seem entirely correct to me -- the GITHUB_ACTOR is the committer of the last commit, but the GITHUB_TOKEN isn't belonging to them. Is that a problem?

Thanks!

**Comment by bobheadxi** [comment]
Glad you're finding the action useful!

Reading up on [`permissions`](https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs) it seems like this is only used to configure the _default_ `GITHUB_TOKEN` (which you don't seem to be using), and I think this is scoped to the specific repository

I'm not sure the clone command is the issue here - locally, for example, this works:

```
# hack from https://stackoverflow.com/questions/42725176/use-git-without-config to skip git config
export GIT_CONFIG_NOSYSTEM=1 GIT_CONFIG=/dev/null HOME=/dev/null GIT_CONFIG_GLOBAL=/dev/null
# make sure I have no config
git config -l

# clone a private repo with an invalid username
git clone https://foobar:$GITHUB_TOKEN@github.com/bobheadxi/pmh.git
```

Could you check that the above works for you locally? If not, it may be that your token has insufficient access

**Comment by srenatus** [comment]
I've found over the weekend that my last attempt from Friday did the trick -- changing the token to a different, more capable one. Thanks for your help!

Btw, side-tracking this, the docs mention that you could use the `action` like this
```
     - name: gobenchdata publish
        run: go run go.bobheadxi.dev/gobenchdata@v1 action
        with:
          GO_TEST_FLAGS: -timeout=120m
          PUBLISH: true
          PUBLISH_BRANCH: benchmarks
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        timeout-minutes: 120
```
i.e. without having all of the stuff in `INPUT_*` vars passed via env. However, `actionlint` said that this was invalid.

(I could contribute updating the docs, but I wanted to check with you first.)
